### ISSUE TITLE
selector interop tests

### ISSUE THREAD

**Issue by Stebalien** [ipld/replication#5]
Instead of writing these after the fact, we should write interop tests up-front (for once). Basically, I'm thinking both go/js should just spit out a stream of json objects for each "event" (e.g., node visited). We can then compare this against some reference traversal.

**Comment by momack2** [comment]
IIRC @vmx is owning the js side interop and reference test suite for stress testing - is that right? @vmx, can you carve this up into milestones and call out any specific go-side work (if any) that would be required to fit into the test suite? Ideally we can keep most of that off @warpfork ‘s plate while he’s deep on graphsync.

**Comment by vmx** [comment]
@momack2 There are the [tests in js-ipld-selectors](https://github.com/vmx/js-ipld-selectors/blob/23be601bcd4557933b154c2fad0891198dd0c666/test/fixtures/README.md) which can be used for interop tests.

I plan to change [dagbuilder](https://github.com/vmx/dagbuilder) to be able to have a simple way to output the blocks in different way. Currently they are stored in an js-ipfs repo, but then you could write a small JS function to store them on disk or into a go-ipfs repo using the HTTP API. 

Then on the Go side someone would need to write the code to take those blocks from disk/the go-ipfs repo and run the selector specified in the fixtures linked above and compare them to the results (which are also part of the fixtures).

What is currently missing is things like a selector returning "i don't have this block", this would be needed to be encoded in the results fixtures.

**Comment by rvagg** [comment]
closing for archival
